[tool.poetry]
name = "meteo"
version = "0.1.0"
description = ""
authors = ["David Hol√Ω <david.holy225@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
neomodel = "*"
flask = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
